export const Formats = [
    "80's Rock",
    'Adult Album Alternative',
    'Adult Contemporary',
    'Adult Hits',
    'Alternative',
    'Americana',
    'Asian',
    'Blues',
    'Business News',
    'Caribbean',
    "Children's",
    'Christian Contemporary',
    'Classic Country',
    'Classic Hip-Hop',
    'Classic Hits',
    'Classic Rock',
    'Classical',
    'College',
    'Comedy',
    'Country',
    'Dance',
    'Easy Listening',
    'Ethnic',
    'Farm',
    'Folk',
    'French',
    'Gospel Music',
    'Grade School (K-12)',
    'Hip-Hop',
    'Hot AC',
    'Jazz',
    'Multinational',
    'Native American',
    'News',
    'News Talk',
    'Nostalgia',
    'Oldies',
    'Other',
    'Public Radio',
    'Regional Mexican',
    'Religious',
    'Rhythmic Oldies',
    'Rock',
    'Smooth Jazz',
    'Spanish',
    'Spanish Christian',
    'Spanish Hits',
    'Spanish News',
    'Spanish Sports',
    'Spanish Talk',
    'Sports',
    'Talk',
    'Tejano',
    'Top-40',
    "Travelers' Information",
    'Tropical',
    'Unknown Format',
    'Urban Contemporary',
    'Variety'
]